resources:
- ns.yaml
- web.yaml
- emoji.yaml
- voting.yaml
- vote-bot.yaml

images:
  - name: emojivoto-web
    newName: ghcr.io/telepresenceio/emojivoto-web
    newTag: 0.2.0
  - name: emojivoto-emoji
    newName: ghcr.io/telepresenceio/emojivoto-emoji
    newTag: 0.2.0
  - name: emojivoto-voting
    newName: ghcr.io/telepresenceio/emojivoto-voting
    newTag: 0.2.0

labels:
  - includeSelectors: true
    pairs:
      version: 0.2.0
  - includeTemplates: false
    pairs:
      app.kubernetes.io/version: 0.2.0