kind: ServiceAccount
apiVersion: v1
metadata:
  name: voting
  namespace: emojivoto
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pv-claim
  namespace: emojivoto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting
  namespace: emojivoto
  labels:
    app.kubernetes.io/name: voting
    app.kubernetes.io/part-of: emojivoto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting
  template:
    metadata:
      labels:
        app: voting
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pv-claim
      serviceAccountName: voting
      containers:
      - env:
        - name: POLL_FILE
          value: '/data/polls.json'
        - name: GRPC_PORT
          value: "8080"
        - name: PROM_PORT
          value: "8801"
        image: emojivoto-voting
        name: voting
        ports:
        - containerPort: 8080
          name: grpc
        - containerPort: 8801
          name: prom
        resources:
          requests:
            cpu: 100m
        volumeMounts:
          - mountPath: "/data"
            name: data
---
apiVersion: v1
kind: Service
metadata:
  name: voting
  namespace: emojivoto
spec:
  selector:
    app: voting
  ports:
  - name: grpc
    port: 8080
    targetPort: grpc
  - name: prom
    port: 8801
    targetPort: prom
