ARG svc_name=nothing

# go build stage
FROM --platform=$BUILDPLATFORM golang:alpine AS golang

WORKDIR /emojivoto-build

# install protobuf
RUN apk add --no-cache make protoc
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

# cache go dependencies
COPY go.mod .
COPY go.sum .
RUN go mod download

# compile
COPY . .
ARG TARGETARCH
ARG TARGETOS
ARG svc_name
RUN GOARCH=$TARGETARCH GOOS=$TARGETOS make -C $svc_name clean protoc compile

# webpack stage
FROM --platform=$BUILDPLATFORM node:alpine AS webpack-bundle
RUN apk --no-cache add make
WORKDIR /emojivoto-build
COPY . .
RUN make -C emojivoto-web clean webpack package-web

FROM golang AS build-emojivoto-emoji-svc
FROM golang AS build-emojivoto-voting-svc
FROM golang AS build-emojivoto-web
COPY --from=webpack-bundle /emojivoto-build/emojivoto-web/target/ /emojivoto-build/emojivoto-web/target/

FROM build-$svc_name AS build

# runtime image
FROM alpine

ARG svc_name
COPY --from=build /emojivoto-build/$svc_name/target/ /usr/local/bin/

# ARG variables are not available for ENTRYPOINT
ENV SVC_NAME=$svc_name
ENTRYPOINT [ "sh", "-c", "/usr/local/bin/$SVC_NAME" ]
