on:
  push:
    tags:
      # These aren't regexps. They are "Workflow Filter patterns"
      - "[0-9]+.[0-9]+.[0-9]"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
      - name: Push image
        env:
          IMAGE_REGISTRY: ghcr.io/telepresenceio
          REF: ${{ github.ref }}
        run: |
          echo '${{ secrets.GITHUB_TOKEN }}' | docker login ghcr.io -u='${{ github.actor }}' --password-stdin
          IMAGE_TAG=${REF#refs/tags/} make push
